const ref = {
  backgroundRoot: {
    css: "background-root",
    desc: "The main site background colour",
    targets: [
      "[Non-IDE] Main site background",
      "Main background (outermost edges, between file, code, console panels)",
    ],
  },
  backgroundDefault: {
    css: "background-default",
    desc: "The main background colour for most elements.",
    targets: [
      "[Non-IDE] Repl card backgrounds",
      "[Non-IDE] Top bar background",
      "File panel background",
      "Active IDE tab background",
      "[Repl control panel] Background",
      "[Main site navigator popout] Background",
    ],
  },
  backgroundHigher: {
    css: "background-higher",
    desc: "Main background colour for hover events on most buttons",
    targets: [
      "[Non-IDE] [Command palette] Background",
      "[Non-IDE] Create repl cards background",
      "[Run button] [Active] Background",
      "Invite button background",
      "Repl language icon border",
      "[Repl control panel] Border",
      "[Repl control panel] Spotlight page button background",
      "[Repl control panel] [Disabled] 'Always on' toggle background",
      "[Repl control panel] 'Add boost' button background",
    ],
  },
  backgroundHighest: {
    css: "background-highest",
    desc: "Element highlight colour",
    targets: [
      "[Non-IDE] Top bar border",
      "[Non-IDE] Repl cards border",
      "[Non-IDE] [Main site navigator panel] Border",
      "[Non-IDE] [Command palette] Options background",
      "[Non-IDE] Tooltip background",
      "Tooltip background",
      "Top bar border",
      "[Main site navigator popout] Border",
      "[Hover] Repl control panel opener border",
    ],
  },
  backgroundOverlay: {
    css: "background-overlay",
    desc: "The colour of the overlay that hides the rest of the screen when certain popups are open",
    targets: [
      "[Main site navigator popout] Overlay background",
      "Invite popup overlay background",
      "[Command palette] Overlay background",
    ],
  },
  foregroundDefault: {
    css: "foreground-default",
    desc: "The main text colour for most text and icons.",
    targets: [
      "[Non-IDE] Tooltip text",
      "[Non-IDE] Card category title text",
      "[Non-IDE] Replit logo",
      "[Non-IDE] Main site navigator popout hamburger icon",
      "[Non-IDE] Main site navigator popout hamburger icon",
      "[Non-IDE] [Main site navigator popout] Option title texts",
      "[Non-IDE] [Main site navigator popout] Username text",
      "[Non-IDE] [Main site navigator popout] Username dropdown option texts",
      "[Non-IDE] [Main site navigator popout] 'Create repl' button text",
      "[Non-IDE] [Main site navigator popout] Main site navigator popout hamburger icon",
      "[Non-IDE] [Main site navigator popout] Light theme icon",
      "[Non-IDE] [Main site navigator popout] Help & shortcuts icon",
      "[Non-IDE] [Command palette] Input text",
      "[Non-IDE] [Command palette] Option text",
      "[Non-IDE] [Command palette] [Hover] Option description text",
      "Main site navigator popout hamburger icon",
      "Replit logo",
      "Repl name text",
      "Repl history icon",
      "Tooltip text",
      "Left panels title text",
      "Active IDE tab name text",
      "[Hover] [Deselected] File name text",
      "Console search & clear icons",
      "[Repl control panel] Name & description",
      "[Repl control panel] Public/private icons",
      "[Repl control panel] Public/private selected text",
      "Command palette icon",
      "[Command palette] Option text",
      "[Command palette] [Hover] Option description",
      "[Command palette] Input text",
    ],
  },
  foregroundDimmer: {
    css: "foreground-dimmer",
    desc: "The main text colour for description text",
    targets: [
      "[Deselected] File name text",
      "Add file & folder icons",
      "[Run button] [Active] Text",
      "Close IDE tab icon",
      "Inactive IDE tab name text",
      "[Command palette] [Deselected] Option description text",
      "[Command palette] Option keyboard shortcut",
      "[Repl control panel] Name & description character count & limit displays",
      "[Repl control panel] [Deselected] Public/private toggle text",
      "[Main site navigator popout] notification icon",
      "Secrets menu subtitle",
      "[Deselected] secrets input box description",
      "Database menu subtitle",
      "Database storage display",
    ],
  },
  foregroundDimmest: {
    css: "foreground-dimmest",
    desc: "The colour for most non-critical icons",
    targets: [
      "Username and Repl name slash divider",
      "[Main site navigator popout] Blog, about, Careers, Pricing, Discord options text",
      "Left panel icons",
      "Add file & folder icon vertical divider",
      "Upload file & folder menu opener icon",
      "[Command palette] Input text icon",
      "[Command palette] [Deselected] Input text description text",
      "Threads message send icon",
    ],
  },
  outlineDimmest: {
    css: "outline-dimmest",
    desc: "The border colour for most menu buttons and tooltips",
    targets: [
      "IDE panel resize drag bars",
      "Console search & clear tooltip borders",
      "Left panel icons tooltip borders",
      "[Repl control panel] Spotlight page button border",
      "[Repl control panel] Name & description input border",
      "[Repl control panel] 'Always on' toggle border",
      "[Repl control panel] 'Add boost' button border",
      "[Command palette] Option keyboard shortcut border (per key)",
    ],
  },
  outlineDefault: {
    css: "outline-default",
    desc: "The outline colour for some non-critical buttons",
    targets: [
      "[Hover] IDE panel resize drag bars",
      "[Hover] Help & shortcuts button border",
      "[Hover] Invite button border",
      "[Hover] Settings dropdown border",
    ],
  },
  outlineDimmer: {
    css: "outline-dimmer",
    targets: [
      "Help & shortcuts tooltip border",
      "[Main site navigator popout] Help & shortcuts tooltip border",
      "[Main site navigator popout] Light theme tooltip border",
    ],
  },
  accentPrimaryDimmest: {
    css: "accent-primary-dimmest",
    desc: "The highlight colour for the currently selected left panel icon",
  },
  accentPrimaryDimmer: {
    css: "accent-primary-dimmer",
    targets: [
      "[Repl control panel] [Hover] Name & description input border",
      "[Main site navigator popout] Create repl button background",
      "Beta label background",
      "[Command palette] [Hover] Option background",
      "[Command palette] [Hover] Option keyboard shortcut border (per key)",
      "[Hover] Secrets input border",
    ],
  },
  accentPrimaryDefault: {
    css: "accent-primary-default",
    desc: "The border colour for most buttons when being pressed",
    targets: [
      "[Selected] File selector background",
      "Username text",
      "[On click] Add file & folder buttons border",
      "[On click] Invite button border",
      "[Replit control panel] [Selected] Name & description input box when mouse is not over",
      "[Replit control panel] [On click] Fork & delete menu icon",
      "[Version control] 'Create a git repo' button background",
      "[Selected] Secrets input boxes when mouse is not over",
      "[On click] Settings dropdown border",
      "[Selected] Settings dropdown item",
      "[Database] 'Replit database' subtitle text",
      "[Command palette] [On click] Clear user input button border",
    ],
  },
  accentPrimaryStronger: {
    css: "accent-primary-stronger",
    targets: [
      "[Repl control panel] Spotlight page button text",
      "[Repl control panel] [Hover] Spotlight page button background",
      "'Send feedback' button text",
      "[Version control] 'Existing git repository?' text",
      "[Main site navigator popout] [Hover] 'Create repo' button border",
      "[Invite popup] 'Generate a new link' text",
      "[Invite popup] Copy invite link button icon",
      "[Invite popup] [Hover] Copy invite link button background",
    ],
  },
  accentPrimaryStrongest: {
    css: "accent-primary-strongest",
    targets: [
      "Beta label text",
      "[Selected] Left panels icon",
      "[Hover] Left panels icon",
    ],
  },
  accentPositiveDimmest: {
    css: "accent-positive-dimmest",
    desc: "The inactive run button",
    targets: [
      "[Run button] Background",
      "[Run button] [Hover] Border",
      "[Repl control panel] Activated boost display background",
    ],
  },
  accentPositiveDimmer: {
    css: "accent-positive-dimmer",
    desc: "The background colour of the popup shown when the client (re)connects to Replit",
    targets: ["'Connected!' popup background"],
  },
  accentPositiveDefault: {
    css: "accent-positive-default",
    targets: [
      "[Run button] [Hover] background",
      "[Repl control panel] Boost button text",
      "[Repl control panel] [Active] Boost message title text",
    ],
  },
  accentPositiveStronger: {
    css: "accent-positive-stronger",
    targets: [
      "[Run button] Text",
      "[Run button] Icon",
      "[Run button] [On click] Border",
    ],
  },
  accentPositiveStrongest: {
    css: "accent-positive-strongest",
    desc: "No observable changes as of yet. Included as it is a good idea to set this to something similar to other positive accents if an element styled with this variable appears for a user.",
    targets: [],
  },
  accentNegativeDimmest: {
    css: "accent-negative-dimmest",
    targets: ["Beta tester ('explorer') button background"],
  },
  accentNegativeDimmer: {
    css: "accent-negative-dimmer",
    targets: "[Main site navigator popout] Notification count label background",
  },
  accentNegativeStronger: {
    css: "accent-negative-stronger",
    targets: [
      "Beta tester ('explorer') button icon",
      "'Unboost Repl' confirm button text",
      "[Hover] 'Unboost Repl' confirm button background",
    ],
  },
  accentNegativeStrongest: {
    css: "accent-negative-strongest",
    targets: [
      "[Main site navigator popout] Notification count label text",
      "[Hover] Beta tester ('explorer') button icon",
    ],
  },
};
